language: node_js

node_js:
  - "8"
  - "10"
  - "11"

sudo: false

script:
  - yarn run build
  - yarn run lint
  - yarn run test
  - yarn run coverage

notifications:
  email:
    tom.kaczocha.code@gmail.com
