#!/usr/bin/env bash

set -e

# Clean
rm -rf dist
mkdir dist

# Copy latent, belonging to the index module
rsync -am . ./dist  --exclude '*/*' --include '*'

# Copy latent files from source, recursively
rsync -am  ./src/* ./dist --exclude '*.ts'

# Build typescript
yarn tsc

rm -rf ./dist/__tests__
rm ./dist/*-resources.json
